language: node_js
node_js: 10

cache:
  directories:
    - frontend/public

git:
  depth: false

env:
  global:
    NODE_ENV=production

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      name: "build"
      install: skip
      script:
        - rm -rf ./frontend/public/js/bundle.js
        - echo "console.log('hello');" >> ./frontend/public/js/bundle.js

    - stage: deploy
      name: "deploy"
      install: skip
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./deploy.sh
