language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - $TRAVIS_BUILD_DIR/public

git:
  depth: false

env:
  global:
    NODE_ENV=production

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      name: "build"
      install: skip
      script:
        - rm -rf public/bundle.js
        - echo "console.log('hello');" >> public/bundle.js

    - stage: deploy
      name: "deploy"
      install: skip
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: if test -f public/bundle.js; then echo "file exists"; else echo "file does not exist"; exit 1; fi
