language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - ./public

git:
  depth: false

env:
  global:
    NODE_ENV=production

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      name: "build"
      install: yarn --production false
      script: yarn clean && yarn build

    - stage: deploy
      name: "deploy"
      install: skip
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./deploy.sh
